# Generated by Django 3.1 on 2020-03-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200301_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Greeting',
            new_name='Party',
        ),
    ]
