# Generated by Django 3.1 on 2020-05-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20200309_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='dateTime',
        ),
        migrations.RemoveField(
            model_name='party',
            name='entryFee',
        ),
        migrations.RemoveField(
            model_name='party',
            name='guysAllowed',
        ),
        migrations.RemoveField(
            model_name='party',
            name='status',
        ),
    ]
