# Generated by Django 3.1 on 2020-05-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20200517_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='entryFee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='guysAllowed',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
